spring.datasource.url=jdbc:mysql://terraform-20250108142447007000000007.c5ymwoeo4u6h.us-east-2.rds.amazonaws.com:3306/springbackend?useSSL=false
spring.datasource.username=admin
spring.datasource.password=Redhat123

spring.jpa.generate-ddl=true
